let g:coc_global_extensions = [
      \    'coc-marketplace',
      \    'coc-css',
      \    'coc-json', 
      \    'coc-tsserver',
      \    'coc-ccls',
      \    'coc-snippets',
      \    'coc-pyright',
      \    'coc-prettier',
      \    'coc-highlight',
      \    'coc-yaml',
      \    '@yaegassy/coc-intelephense',
      \    'coc-sql',
      \    'coc-floaterm',
      \    'coc-emmet',
      \    'coc-html',
      \    'coc-vimlsp',
      \    'coc-phpls'
      \  ]
