require("core.plugin_config.gruvbox")
require("core.plugin_config.lualine")
require("core.plugin_config.nvim-tree")
require("core.plugin_config.telescope")
require("core.plugin_config.floaterm")
require("core.plugin_config.bufferline")
require("core.plugin_config.whichkey")

require("core.plugin_config.vim-sneak")
require("core.plugin_config.gitgutter")
require("core.plugin_config.autocompletion")
require("core.plugin_config.snippets")
